services:
  - type: web
    name: piffystudio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: piffy-db
          property: connectionString

databases:
  - name: piffy-db
    plan: free
    engine: postgresql
    version: "14"